version: '3'
services:
  mongodb:
    image: mongo
    ports:
    - 27017:27017
    environmet:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INTDB_ROOT_PASSWORD=password 
  mongo-express:
    image: mongo-express
    ports:
    - 8080:8081
    environmet:
    - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
    - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    - ME_CONFIG_MONGODB_SERVER=mongodb