FROM node:13-alpine
ENV MONGO_DB_USERNAME=admin MONGO_DB_PWD=password
RUN mkdir -p /home/app
COPY . /home/app
CMD ["node","server.js"]

_______________________

FROM node:18-alpine AS builder
WORKDIR /usr/src/app
COPY app/movie-analyst-api/package*.json ./
RUN npm install
COPY app/movie-analyst-api/ .
FROM node:18-alpine
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app ./
RUN chown -R node:node /usr/src/app
USER node
EXPOSE 3000
ENV NODE_ENV=production
CMD [ "node", "server.js"]