{
 "title": "HTTP RED - python-redis-pg",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "HTTP in-flight requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (http_target) (http_server_active_requests)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP avg latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (http_target) (\n  rate(http_server_duration_milliseconds_sum[5m])\n)\n/\nsum by (http_target) (\n  rate(http_server_duration_milliseconds_count[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP p95 latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, http_target) (\n    rate(http_server_duration_milliseconds_bucket[5m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (http_target) (\n  rate(http_server_duration_milliseconds_count[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}