apiVersion: 1

datasources:
  - name: AWS CloudWatch
    uid: aws-cloudwatch
    type: cloudwatch
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      authType: default
      defaultRegion: ${AWS_REGION}
